# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productfeatured_text_css_color'),
        ('carts', '0002_remove_cart_itemlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='itemList',
            field=models.ManyToManyField(through='carts.CartItem', to='products.Variation'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Cart'),
            preserve_default=False,
        ),
    ]
