# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productfeatured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='make_img_background',
            field=models.BooleanField(default=False),
        ),
    ]
