# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170308_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeatured',
            name='text_css_color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
